name: Unit testing
on: [push]
jobs:
  unit-test-run:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    name: Unit tests on Node v${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run test-ci
        env:
          CI: true
