name: Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run build --if-present
      - run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
