name: Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run build --if-present
      - run: git config --global user.email "vsilvestre.pro@gmail.com"
      - run: git config --global user.name "vasilvestre"
      - run: git remote set-url origin https://${{ secrets.REPO_TOKEN }}@github.com/vasilvestre/FNCS.git
      - run: npm run deploy
